///----AUTH CONSTANTS----///
export const LOGIN_USER_AWAIT = 'LOGIN_USER_AWAIT';
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOG_OFF = 'LOG_OFF';

export const REGISTER_USER_AWAIT = 'REGISTER_USER_AWAIT';
export const REGISTER_USER_FAIL = 'REGISTER_USER_FAIL';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';


///----GROCERY LIST CONSTANTS----///
export const ADD_LIST_AWAIT = 'ADD_LIST_AWAIT';
export const ADD_LIST_FAIL = 'ADD_LIST_FAIL';
export const ADD_LIST_SUCCESS = 'ADD_LIST_SUCCESS';

export const REMOVE_LIST_AWAIT = 'REMOVE_LIST_AWAIT';
export const REMOVE_LIST_FAIL = 'REMOVE_LIST_FAIL';
export const REMOVE_LIST_SUCCESS = 'REMOVE_LIST_SUCCESS';

export const GET_LIST_AWAIT = 'GET_LIST_AWAIT';
export const GET_LIST_FAIL = 'GET_LIST_FAIL';
export const GET_LIST_SUCCESS = 'GET_LIST_SUCCESS';
export const GET_LIST_CANCELLED = 'GET_LIST_CANCELLED';

export const EDIT_LIST_NAME_AWAIT = 'EDIT_LIST_NAME_AWAIT';
export const EDIT_LIST_NAME_FAIL = 'EDIT_LIST_NAME_FAIL';
export const EDIT_LIST_NAME_SUCCESS = 'EDIT_LIST_NAME_SUCCESS';

export const SHOW_OPTIMISTIC_LIST = 'SHOW_OPTIMISTIC_LIST';

///----GROCERY ITEMS CONSTANTS----///
export const ADD_ITEMS_AWAIT = 'ADD_ITEMS_AWAIT';
export const ADD_ITEMS_FAIL = 'ADD_ITEMS_FAIL';
export const ADD_ITEMS_SUCCESS = 'ADD_ITEMS_SUCCESS';

export const REMOVE_ITEMS_AWAIT = 'REMOVE_ITEMS_AWAIT';
export const REMOVE_ITEMS_FAIL = 'REMOVE_ITEMS_FAIL';
export const REMOVE_ITEMS_SUCCESS = 'REMOVE_ITEMS_SUCCESS';

export const COMPLETE_ITEMS_AWAIT = 'COMPLETE_ITEMS_AWAIT';
export const COMPLETE_ITEMS_FAIL = 'COMPLETE_ITEMS_FAIL';
export const COMPLETE_ITEMS_SUCCESS = 'COMPLETE_ITEMS_SUCCESS';

export const EDIT_ITEMS_AWAIT = 'EDIT_ITEMS_AWAIT';
export const EDIT_ITEMS_FAIL = 'EDIT_ITEMS_FAIL';
export const EDIT_ITEMS_SUCCESS = 'EDIT_ITEMS_SUCCESS';
