export const LOGIN_USER_AWAIT = 'LOGIN_USER_AWAIT';
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';

export const REGISTER_USER_AWAIT = 'REGISTER_USER_AWAIT';
export const REGISTER_USER_FAIL = 'REGISTER_USER_FAIL';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';

export const LOG_OFF = 'LOG_OFF';
